apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    repoURL: https://github.com/AlexanderWiechert/k3s-playground
    targetRevision: HEAD
    path: kustomize/base
    kustomize:
      version: v4.5.7
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 

