apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 44.3.0
    helm:
      skipCrds: true
      values: |-    
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - Replace=true
    automated:
      prune: true
      selfHeal: true